import React,{useEffect,useMemo,useState} from 'react';
import {SafeAreaView,ScrollView,View,Text,TextInput,Pressable,StyleSheet,ActivityIndicator,Alert} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {StatusBar} from 'expo-status-bar';
import {JURS,TURNOS,Tabla,calcularVF} from './src/engine';
import {CabezasDia,descargarCabezas} from './src/cabezas';
const KEY='vf_cabezas_v3',LOG='vf_predicciones_v1',AUTO='vf_cabezas_auto_v1';
const empty=():Tabla=>Object.fromEntries(JURS.map(j=>[j,'']));
const fmt=(x:string)=>x&&x!=='----'?x:'----';
export default function App(){
 const [fecha,setFecha]=useState(new Date().toISOString().slice(0,10)),[turno,setTurno]=useState('Nocturno'),[tabs,setTabs]=useState<Record<string,Tabla>>({Anterior:empty()}),[out,setOut]=useState<any>(null),[busy,setBusy]=useState(false),[screen,setScreen]=useState<'vf'|'cabezas'>('vf'),[auto,setAuto]=useState<CabezasDia|null>(null),[updated,setUpdated]=useState('');
 const necesarios=useMemo(()=>['Anterior',...TURNOS.slice(0,TURNOS.indexOf(turno as any))],[turno]);
 useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>x&&setTabs(JSON.parse(x))).catch(()=>{});AsyncStorage.getItem(AUTO).then(x=>{if(x){const q=JSON.parse(x);setAuto(q.data);setUpdated(q.updated||'')}}).catch(()=>{})},[]);
 const set=(t:string,j:string,v:string)=>{const n={...tabs,[t]:{...(tabs[t]||empty()),[j]:v.replace(/\D/g,'').slice(0,4)}};setTabs(n);AsyncStorage.setItem(KEY,JSON.stringify(n))};
 const actualizar=async()=>{try{setBusy(true);const data=await descargarCabezas();const stamp=new Date().toLocaleString();setAuto(data);setUpdated(stamp);await AsyncStorage.setItem(AUTO,JSON.stringify({data,updated:stamp}));const n={...tabs};for(const t of TURNOS)n[t]={...(n[t]||empty()),...data[t]};setTabs(n);await AsyncStorage.setItem(KEY,JSON.stringify(n));}catch(e:any){Alert.alert('No se pudieron actualizar las cabezas',`${e?.message||e}\n\nSe mantienen los últimos datos guardados y la carga manual.`)}finally{setBusy(false)}};
 const calc=()=>{try{setBusy(true);const hist=necesarios.map(t=>{let z=tabs[t]||empty();if(t!=='Anterior'&&auto?.[t])z={...auto[t],...z};return Object.fromEntries(JURS.map(j=>[j,z[j]?z[j].padStart(4,'0'):'----'])) as Tabla});const r=calcularVF(hist);setOut(r);AsyncStorage.getItem(LOG).then(x=>{const q=x?JSON.parse(x):{};q[`${fecha}_${turno}`]={fecha,turno,...r};return AsyncStorage.setItem(LOG,JSON.stringify(q))}).catch(()=>{});}catch(e:any){Alert.alert('Error VF',e?.message||String(e))}finally{setBusy(false)}};
 const rank=(title:string,rows:any[],numKey='numero',scoreKey='score')=><View style={s.block}><Text style={s.rhead}>{title}</Text>{rows.map((x:any,i:number)=><Text style={s.txt} key={`${title}-${x[numKey]}`}>{i+1}. {x[numKey]}  {Number(x[scoreKey]).toFixed(6)}</Text>)}</View>;
 const heads=()=> <><View style={s.headRow}><View><Text style={s.h2}>Cabezas del día</Text><Text style={s.small}>{updated?`Última actualización: ${updated}`:'Todavía sin actualizar'}</Text></View><Pressable style={s.refresh} onPress={actualizar} disabled={busy}><Text style={s.goT}>{busy?'...':'↻ ACTUALIZAR'}</Text></Pressable></View><ScrollView horizontal><View><View style={s.tableRow}><Text style={[s.cell,s.first]}>Jurisdicción</Text>{TURNOS.map(t=><Text key={t} style={s.cell}>{t}</Text>)}</View>{JURS.map(j=><View key={j} style={s.tableRow}><Text style={[s.cell,s.first,s.jbold]}>{j}</Text>{TURNOS.map(t=><Text key={t} style={[s.cell,auto?.[t]?.[j]&&auto[t][j]!=='----'?s.ready:s.pending]}>{fmt(auto?.[t]?.[j]||'----')}</Text>)}</View>)}</View></ScrollView><Text style={s.help}>Los datos descargados se guardan en el teléfono y VF los reutiliza. Si la fuente no responde, podés seguir cargando manualmente.</Text></>;
 return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.nav}><Pressable style={[s.navBtn,screen==='vf'&&s.navOn]} onPress={()=>setScreen('vf')}><Text style={s.navTxt}>VF</Text></Pressable><Pressable style={[s.navBtn,screen==='cabezas'&&s.navOn]} onPress={()=>setScreen('cabezas')}><Text style={s.navTxt}>CABEzas</Text></Pressable></View><ScrollView contentContainerStyle={s.page}><Text style={s.h1}>VF QUINIELA</Text>{screen==='cabezas'?heads():<><Text style={s.sub}>V7 + V8 + V9 + V11 + V13 + V14</Text><Pressable style={s.autoBtn} onPress={actualizar} disabled={busy}><Text style={s.goT}>{busy?'ACTUALIZANDO...':'↻ CARGAR CABEZAS AUTOMÁTICAMENTE'}</Text></Pressable>{updated?<Text style={s.smallCenter}>Datos guardados: {updated}</Text>:null}<Text style={s.label}>Fecha objetivo</Text><TextInput style={s.input} value={fecha} onChangeText={setFecha}/><Text style={s.label}>Turno objetivo</Text><View style={s.chips}>{TURNOS.map(t=><Pressable key={t} onPress={()=>{setTurno(t);setOut(null)}} style={[s.chip,turno===t&&s.on]}><Text style={s.ct}>{t}</Text></Pressable>)}</View>{necesarios.map(t=><View key={t} style={s.card}><Text style={s.title}>{t==='Anterior'?'Nocturna anterior':t}</Text>{JURS.map(j=><View key={j} style={s.row}><Text style={s.j}>{j}</Text><TextInput keyboardType="number-pad" placeholder={t!=='Anterior'&&auto?.[t]?.[j]?auto[t][j]:'----'} placeholderTextColor="#777" style={s.num} value={(tabs[t]||{})[j]||''} onChangeText={v=>set(t,j,v)}/></View>)}</View>)}<Pressable style={s.go} onPress={calc} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.goT}>CALCULAR VF COMPLETO</Text>}</Pressable>{out&&<View style={s.result}><Text style={s.rhead}>VF — RESUMEN FINAL</Text><Text style={s.decision}>V11: {out.v11}   ·   V14: {out.v14}</Text><Text style={s.small}>Conf: V7 {out.conf.V7.toFixed(4)} · V8 {out.conf.V8.toFixed(4)} · V9 {out.conf.V9.toFixed(4)}</Text><Text style={s.small}>EV: V7 {out.ev.V7.toFixed(4)} · V11 {out.ev.V11.toFixed(4)} · V13 {out.ev.V13.toFixed(4)}</Text><Text style={s.big}>TOP 2: {out.top2.join(' · ')}</Text><Text style={s.big}>TOP 5: {out.top5.join(' · ')}</Text><Text style={s.txt}>Ocultos 6–10: {out.ocultos.join(' · ')||'—'}</Text><Text style={s.txt}>Alternativos: {out.alternativos.join(' · ')||'—'}</Text><Text style={s.txt}>Coincidencias: {out.consenso.join(' · ')||'—'}</Text><Text style={s.txt}>2 cifras: {out.dos.slice(0,5).map((x:any)=>`${x[0]}(${x[1]})`).join(' · ')}</Text><Text style={s.txt}>Convicción V9: {out.conviccionV9}</Text>{rank('V7 — TOP 10',out.v7)}{rank('V8 — TOP 10',out.v8)}{rank('V9 — TOP 10',out.v9)}{rank('V13 — META-RANKER',out.v13,'cand','meta')}</View>}</>}<Text style={s.note}>Fuente de cabezas: Viví tu Suerte. Sistema experimental; los sorteos son aleatorios y no garantiza aciertos.</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#09070d'},nav:{flexDirection:'row',padding:8,backgroundColor:'#110d17'},navBtn:{flex:1,padding:11,borderRadius:10},navOn:{backgroundColor:'#6d28d9'},navTxt:{color:'#fff',fontWeight:'900',textAlign:'center'},page:{padding:18,paddingBottom:60},h1:{fontSize:30,fontWeight:'900',color:'#fff',textAlign:'center',marginTop:14},h2:{fontSize:22,fontWeight:'900',color:'#fff'},sub:{color:'#a78bfa',textAlign:'center',marginBottom:14},label:{color:'#ddd',fontWeight:'700',marginTop:10,marginBottom:6},input:{backgroundColor:'#17131f',borderWidth:1,borderColor:'#382a4b',color:'#fff',borderRadius:10,padding:12},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:12},chip:{paddingVertical:8,paddingHorizontal:10,borderRadius:20,backgroundColor:'#20192b'},on:{backgroundColor:'#6d28d9'},ct:{color:'#fff',fontSize:12},card:{backgroundColor:'#141019',borderRadius:14,padding:14,marginTop:12,borderWidth:1,borderColor:'#2d223b'},title:{color:'#c4b5fd',fontSize:18,fontWeight:'800',marginBottom:8},row:{flexDirection:'row',alignItems:'center',marginVertical:4},j:{color:'#ddd',flex:1},num:{width:90,backgroundColor:'#08070b',color:'#fff',borderRadius:8,padding:9,textAlign:'center',fontSize:17},go:{backgroundColor:'#7c3aed',padding:16,borderRadius:14,marginTop:20},autoBtn:{backgroundColor:'#4c1d95',padding:13,borderRadius:12,marginBottom:4},goT:{color:'#fff',fontWeight:'900',textAlign:'center'},result:{backgroundColor:'#121017',borderRadius:14,padding:15,marginTop:18},block:{marginTop:8,paddingTop:5,borderTopWidth:1,borderTopColor:'#2b2233'},rhead:{color:'#a78bfa',fontWeight:'900',fontSize:17,marginTop:12,marginBottom:7},decision:{color:'#fff',fontWeight:'900',fontSize:18,marginBottom:5},big:{color:'#fff',fontWeight:'800',fontSize:18,lineHeight:28,marginTop:7},txt:{color:'#ddd',lineHeight:23},small:{color:'#aaa',fontSize:12,lineHeight:18},smallCenter:{color:'#888',fontSize:11,textAlign:'center',marginBottom:8},note:{color:'#777',fontSize:11,textAlign:'center',marginTop:25},headRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:16},refresh:{backgroundColor:'#6d28d9',padding:11,borderRadius:10},tableRow:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:'#2b2233'},cell:{width:92,paddingVertical:11,paddingHorizontal:5,color:'#ddd',textAlign:'center'},first:{width:115,textAlign:'left'},jbold:{fontWeight:'800',color:'#fff'},ready:{color:'#c4b5fd',fontWeight:'800'},pending:{color:'#666'},help:{color:'#999',lineHeight:19,marginTop:18}});