import React,{useEffect,useMemo,useState} from 'react';
import {SafeAreaView,ScrollView,View,Text,TextInput,Pressable,StyleSheet,ActivityIndicator,Alert,Platform,StatusBar as RNStatusBar} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {StatusBar} from 'expo-status-bar';
import {JURS,TURNOS,Tabla,calcularVF} from './src/engine';
import {CabezasDia,descargarCabezas} from './src/cabezas';
const KEY='vf_cabezas_v3',LOG='vf_predicciones_v1',AUTO='vf_cabezas_auto_v3';
const empty=():Tabla=>Object.fromEntries(JURS.map(j=>[j,''])); const fmt=(x:string)=>x&&x!=='----'?x:'----';
const isoToday=()=>new Date().toISOString().slice(0,10); const display=(iso:string)=>{const [y,m,d]=iso.split('-');return y&&m&&d?`${d}/${m}/${y}`:iso};
const toIso=(v:string)=>{const m=v.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(!m)return null;const [,d,mo,y]=m;const dt=new Date(`${y}-${mo}-${d}T12:00:00`);return dt.getFullYear()===+y&&dt.getMonth()+1===+mo&&dt.getDate()===+d?`${y}-${mo}-${d}`:null};
const maskDate=(v:string)=>{const n=v.replace(/\D/g,'').slice(0,8);return n.length<=2?n:n.length<=4?`${n.slice(0,2)}/${n.slice(2)}`:`${n.slice(0,2)}/${n.slice(2,4)}/${n.slice(4)}`};
const yesterday=(f:string)=>{const d=new Date(`${f}T12:00:00`);d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)};
export default function App(){
 const today=isoToday();const [fecha,setFecha]=useState(today),[fechaText,setFechaText]=useState(display(today)),[fechaCabezas,setFechaCabezas]=useState(today),[fechaCabezasText,setFechaCabezasText]=useState(display(today)),[turno,setTurno]=useState('Nocturno'),[tabs,setTabs]=useState<Record<string,Tabla>>({Anterior:empty()}),[out,setOut]=useState<any>(null),[busy,setBusy]=useState(false),[screen,setScreen]=useState<'vf'|'cabezas'>('vf'),[auto,setAuto]=useState<CabezasDia|null>(null),[updated,setUpdated]=useState('');
 const necesarios=useMemo(()=>['Anterior',...TURNOS.slice(0,TURNOS.indexOf(turno as any))],[turno]);
 useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>x&&setTabs(JSON.parse(x))).catch(()=>{})},[]);
 const set=(t:string,j:string,v:string)=>{const n={...tabs,[t]:{...(tabs[t]||empty()),[j]:v.replace(/\D/g,'').slice(0,4)}};setTabs(n);AsyncStorage.setItem(KEY,JSON.stringify(n))};
 const load=async(iso:string,applyVF:boolean)=>{try{setBusy(true);const [data,prev]=await Promise.all([descargarCabezas(iso),descargarCabezas(yesterday(iso)).catch(()=>null)]);const stamp=new Date().toLocaleString();setAuto(data);setUpdated(stamp);await AsyncStorage.setItem(AUTO,JSON.stringify({fecha:iso,data,updated:stamp}));if(applyVF){const n={...tabs};for(const t of TURNOS)n[t]={...(n[t]||empty()),...data[t]};if(prev)n.Anterior={...(n.Anterior||empty()),...prev.Nocturno};setTabs(n);await AsyncStorage.setItem(KEY,JSON.stringify(n));}}catch(e:any){Alert.alert('No se pudieron actualizar las cabezas',`${e?.message||e}\n\nSe mantienen los últimos datos guardados y la carga manual.`)}finally{setBusy(false)}};
 const actualizarVF=()=>{const iso=toIso(fechaText);if(!iso)return Alert.alert('Fecha inválida','Usá el formato DD/MM/AAAA, por ejemplo 05/10/2026.');setFecha(iso);load(iso,true)};
 const actualizarCabezas=()=>{const iso=toIso(fechaCabezasText);if(!iso)return Alert.alert('Fecha inválida','Usá el formato DD/MM/AAAA, por ejemplo 05/10/2026.');setFechaCabezas(iso);load(iso,false)};
 const calc=()=>{const iso=toIso(fechaText);if(!iso)return Alert.alert('Fecha inválida','Usá DD/MM/AAAA.');setFecha(iso);try{setBusy(true);const hist=necesarios.map(t=>{const z=tabs[t]||empty();return Object.fromEntries(JURS.map(j=>[j,z[j]?z[j].padStart(4,'0'):'----'])) as Tabla});const r=calcularVF(hist);setOut(r);AsyncStorage.getItem(LOG).then(x=>{const q=x?JSON.parse(x):{};q[`${iso}_${turno}`]={fecha:iso,turno,...r};return AsyncStorage.setItem(LOG,JSON.stringify(q))}).catch(()=>{});}catch(e:any){Alert.alert('Error VF',e?.message||String(e))}finally{setBusy(false)}};
 const rank=(title:string,rows:any[],numKey='numero',scoreKey='score')=><View style={s.block}><Text style={s.rhead}>{title}</Text>{rows.map((x:any,i:number)=><Text style={s.txt} key={`${title}-${x[numKey]}`}>{i+1}. {x[numKey]}  {Number(x[scoreKey]).toFixed(6)}</Text>)}</View>;
 const dateInput=(value:string,onChange:(v:string)=>void)=><><TextInput keyboardType="number-pad" maxLength={10} style={s.input} value={value} onChangeText={v=>onChange(maskDate(v))} placeholder="DD/MM/AAAA" placeholderTextColor="#777"/><Text style={s.dateHint}>Formato: DD/MM/AAAA</Text></>;
 const heads=()=> <><View style={s.headRow}><View style={{flex:1}}><Text style={s.h2}>Cabezas</Text><Text style={s.small}>{updated?`Última actualización: ${updated}`:'Todavía sin actualizar'}</Text></View></View><Text style={s.label}>Fecha de consulta</Text>{dateInput(fechaCabezasText,v=>{setFechaCabezasText(v);setAuto(null);setUpdated('')})}<Pressable style={s.refreshWide} onPress={actualizarCabezas} disabled={busy}><Text style={s.goT}>{busy?'...':'↻ ACTUALIZAR CABEZAS'}</Text></Pressable><ScrollView horizontal><View><View style={s.tableRow}><Text style={[s.cell,s.first]}>Jurisdicción</Text>{TURNOS.map(t=><Text key={t} style={s.cell}>{t}</Text>)}</View>{JURS.map(j=><View key={j} style={s.tableRow}><Text style={[s.cell,s.first,s.jbold]}>{j}</Text>{TURNOS.map(t=><Text key={t} style={[s.cell,auto?.[t]?.[j]&&auto[t][j]!=='----'?s.ready:s.pending]}>{fmt(auto?.[t]?.[j]||'----')}</Text>)}</View>)}</View></ScrollView><Text style={s.help}>Esta fecha es independiente de la fecha del pronóstico VF. Sirve para consultar cualquier jornada sin modificar tu predicción.</Text></>;
 return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.nav}><Pressable style={[s.navBtn,screen==='vf'&&s.navOn]} onPress={()=>setScreen('vf')}><Text style={s.navTxt}>VF</Text></Pressable><Pressable style={[s.navBtn,screen==='cabezas'&&s.navOn]} onPress={()=>setScreen('cabezas')}><Text style={s.navTxt}>CABEZAS</Text></Pressable></View><ScrollView contentContainerStyle={s.page}><Text style={s.h1}>VF QUINIELA</Text>{screen==='cabezas'?heads():<><Text style={s.sub}>V7 + V8 + V9 + V11 + V13 + V14</Text><Pressable style={s.autoBtn} onPress={actualizarVF} disabled={busy}><Text style={s.goT}>{busy?'ACTUALIZANDO...':'↻ CARGAR CABEZAS AUTOMÁTICAMENTE'}</Text></Pressable><Text style={s.label}>Fecha objetivo</Text>{dateInput(fechaText,v=>{setFechaText(v);setOut(null)})}<Text style={s.label}>Turno objetivo</Text><View style={s.chips}>{TURNOS.map(t=><Pressable key={t} onPress={()=>{setTurno(t);setOut(null)}} style={[s.chip,turno===t&&s.on]}><Text style={s.ct}>{t}</Text></Pressable>)}</View>{necesarios.map(t=><View key={t} style={s.card}><Text style={s.title}>{t==='Anterior'?'Nocturna anterior':t}</Text>{JURS.map(j=><View key={j} style={s.row}><Text style={s.j}>{j}</Text><TextInput keyboardType="number-pad" placeholder="----" placeholderTextColor="#777" style={s.num} value={(tabs[t]||{})[j]||''} onChangeText={v=>set(t,j,v)}/></View>)}</View>)}<Pressable style={s.go} onPress={calc} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.goT}>CALCULAR VF COMPLETO</Text>}</Pressable>{out&&<View style={s.result}><Text style={s.rhead}>VF — RESUMEN FINAL</Text><Text style={s.decision}>V11: {out.v11}   ·   V14: {out.v14}</Text><Text style={s.small}>Conf: V7 {out.conf.V7.toFixed(4)} · V8 {out.conf.V8.toFixed(4)} · V9 {out.conf.V9.toFixed(4)}</Text><Text style={s.small}>EV: V7 {out.ev.V7.toFixed(4)} · V11 {out.ev.V11.toFixed(4)} · V13 {out.ev.V13.toFixed(4)}</Text><Text style={s.big}>TOP 2: {out.top2.join(' · ')}</Text><Text style={s.big}>TOP 5: {out.top5.join(' · ')}</Text><Text style={s.txt}>Ocultos 6–10: {out.ocultos.join(' · ')||'—'}</Text><Text style={s.txt}>Alternativos: {out.alternativos.join(' · ')||'—'}</Text><Text style={s.txt}>Coincidencias: {out.consenso.join(' · ')||'—'}</Text><Text style={s.txt}>2 cifras: {out.dos.slice(0,5).map((x:any)=>`${x[0]}(${x[1]})`).join(' · ')}</Text><Text style={s.txt}>Convicción V9: {out.conviccionV9}</Text>{rank('V7 — TOP 10',out.v7)}{rank('V8 — TOP 10',out.v8)}{rank('V9 — TOP 10',out.v9)}{rank('V13 — META-RANKER',out.v13,'cand','meta')}</View>}</>}<Text style={s.note}>Fuente de cabezas: Viví tu Suerte. Sistema experimental; los sorteos son aleatorios y no garantiza aciertos.</Text></ScrollView></SafeAreaView>}
const topInset=Platform.OS==='android'?(RNStatusBar.currentHeight||24)+8:8;
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#09070d',paddingTop:topInset},nav:{flexDirection:'row',paddingHorizontal:12,paddingVertical:8,backgroundColor:'#110d17',gap:8},navBtn:{flex:1,paddingVertical:13,borderRadius:12},navOn:{backgroundColor:'#6d28d9'},navTxt:{color:'#fff',fontWeight:'900',textAlign:'center'},page:{padding:18,paddingBottom:60},h1:{fontSize:30,fontWeight:'900',color:'#fff',textAlign:'center',marginTop:14},h2:{fontSize:22,fontWeight:'900',color:'#fff'},sub:{color:'#a78bfa',textAlign:'center',marginBottom:14},label:{color:'#ddd',fontWeight:'700',marginTop:10,marginBottom:6},input:{backgroundColor:'#17131f',borderWidth:1,borderColor:'#382a4b',color:'#fff',borderRadius:10,padding:12,fontSize:16},dateHint:{color:'#777',fontSize:11,marginTop:4,marginLeft:3},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:12},chip:{paddingVertical:8,paddingHorizontal:10,borderRadius:20,backgroundColor:'#20192b'},on:{backgroundColor:'#6d28d9'},ct:{color:'#fff',fontSize:12},card:{backgroundColor:'#141019',borderRadius:14,padding:14,marginTop:12,borderWidth:1,borderColor:'#2d223b'},title:{color:'#c4b5fd',fontSize:18,fontWeight:'800',marginBottom:8},row:{flexDirection:'row',alignItems:'center',marginVertical:4},j:{color:'#ddd',flex:1},num:{width:90,backgroundColor:'#08070b',color:'#fff',borderRadius:8,padding:9,textAlign:'center',fontSize:17},go:{backgroundColor:'#7c3aed',padding:16,borderRadius:14,marginTop:20},autoBtn:{backgroundColor:'#4c1d95',padding:13,borderRadius:12,marginBottom:4},goT:{color:'#fff',fontWeight:'900',textAlign:'center'},result:{backgroundColor:'#121017',borderRadius:14,padding:15,marginTop:18},block:{marginTop:8,paddingTop:5,borderTopWidth:1,borderTopColor:'#2b2233'},rhead:{color:'#a78bfa',fontWeight:'900',fontSize:17,marginTop:12,marginBottom:7},decision:{color:'#fff',fontWeight:'900',fontSize:18,marginBottom:5},big:{color:'#fff',fontWeight:'800',fontSize:18,lineHeight:28,marginTop:7},txt:{color:'#ddd',lineHeight:23},small:{color:'#aaa',fontSize:12,lineHeight:18},note:{color:'#777',fontSize:11,textAlign:'center',marginTop:25},headRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:4},refreshWide:{backgroundColor:'#6d28d9',padding:13,borderRadius:10,marginTop:10,marginBottom:16},tableRow:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:'#2b2233'},cell:{width:92,paddingVertical:11,paddingHorizontal:5,color:'#ddd',textAlign:'center'},first:{width:115,textAlign:'left'},jbold:{fontWeight:'800',color:'#fff'},ready:{color:'#c4b5fd',fontWeight:'800'},pending:{color:'#666'},help:{color:'#999',lineHeight:19,marginTop:18}});