import {MODEL_V7,TRAIN_V11,TRAIN_V13,TRAIN_V14} from './frozenData';
export const TURNOS=['Previa','Primera','Matutino','Vespertino','Nocturno'] as const;
export const JURS=['Ciudad','Provincia','Córdoba','Santa Fé','Entre Ríos','Montevideo'] as const;
export type Tabla=Record<string,string>; type P=[number,number];
const DIRS:P[]=[];for(const a of [-1,0,1])for(const b of [-1,0,1])if(a||b)DIRS.push([a,b]);
const mas11=(n:string)=>String((Number(n.padStart(4,'0').slice(-2))+11)%100).padStart(2,'0');
export function tableroManual(hist:Tabla[]){const G:(string|null)[][]=[];for(const j of JURS){const row:(string|null)[]=[];for(const t of hist){const n=t[j];row.push(...(n&&n!=='----'?mas11(n).split(''):[null,null]));}G.push(row)}const ages:number[]=[];for(let k=0;k<hist.length;k++)ages.push(k,k);return {G,ages}}
function candidatos(G:(string|null)[][]){const out=new Map<string,P[][]>(),R=G.length,C=G[0]?.length||0;for(let r=0;r<R;r++)for(let c=0;c<C;c++){if(G[r][c]==null)continue;for(const d1 of DIRS){const a:P=[r+d1[0],c+d1[1]];if(a[0]<0||a[0]>=R||a[1]<0||a[1]>=C||G[a[0]][a[1]]==null)continue;for(const d2 of DIRS){const b:P=[a[0]+d2[0],a[1]+d2[1]];if(b[0]<0||b[0]>=R||b[1]<0||b[1]>=C||G[b[0]][b[1]]==null||(b[0]===r&&b[1]===c))continue;const p:P[]=[[r,c],a,b],s=p.map(([x,y])=>G[x][y]).join('');const q=out.get(s)||[];q.push(p);out.set(s,q)}}}return out}
function temporalFeat(s:string,paths:P[][],G:(string|null)[][],ages:number[]){let cross=0,same=0;for(const p of paths){const aa=p.map(([,c])=>ages[c]);cross=Math.max(cross,new Set(aa).size);same=Math.max(same,Number(new Set(p.map(([,c])=>Math.floor(c/2))).size===1))}const freq=new Map<string,number>();for(const row of G)for(const x of row)if(x!=null)freq.set(x,(freq.get(x)||0)+1);const support=[...s].reduce((a,d)=>a+(freq.get(d)||0),0),nsrc=ages.length?Math.max(...ages)+1:0,ts:number[]=[];for(const d of s){let cnt=0;for(let age=0;age<nsrc;age++){const cols=ages.map((a,i)=>a===age?i:-1).filter(i=>i>=0);if(G.some(row=>cols.some(c=>row[c]===d)))cnt++}ts.push(cnt)}return [Math.min(cross,3),Math.min(Math.min(...ts),3),Math.min(ts.reduce((a,b)=>a+b,0),8),Math.min(support,15),same]}
export type V7Row={numero:string;score:number;caminos:number};
export function v7(hist:Tabla[]):V7Row[]{const {G,ages}=tableroManual(hist),C=candidatos(G),hit=MODEL_V7.hit as Record<string,number>,allc=MODEL_V7.allc as Record<string,number>;const globalRate=(Object.values(hit).reduce((a,b)=>a+b,0)+1)/(Object.values(allc).reduce((a,b)=>a+b,0)+100);const out:V7Row[]=[];for(const [s,paths] of C){const key=temporalFeat(s,paths,G,ages).join(','),rate=((hit[key]||0)+20*globalRate)/((allc[key]||0)+20),score=Math.log(rate+1e-12)+.04*Math.log1p(Math.min(paths.length,8));out.push({numero:s,score,caminos:paths.length})}return out.sort((a,b)=>b.score-a.score||a.numero.localeCompare(b.numero))}
const src=(c:number)=>Math.floor(c/2);
export type V8Row={numero:string;score:number;caminos:number;c0:number;solo_c0:number;fuentes:number;horizontal:number};
export function v8(hist:Tabla[]):V8Row[]{const {G,ages}=tableroManual(hist),C=candidatos(G),total=ages.length?Math.max(...ages)+1:1,out:V8Row[]=[];for(const [numero,ps] of C){const n=Math.max(ps.length,1),touch=ps.filter(p=>p.some(([,c])=>src(c)===0)).length,solo=ps.filter(p=>p.every(([,c])=>src(c)===0)).length,h=ps.filter(p=>new Set(p.map(([r])=>r)).size===1).length,fuentes=new Set(ps.flat().map(([,c])=>src(c))).size/Math.max(total,1),c0=touch/n,horizontal=h/n,conf=Math.min(Math.log1p(ps.length)/Math.log(9),1);out.push({numero,score:.55*c0+.30*fuentes+.05*horizontal+.10*conf,caminos:ps.length,c0,solo_c0:solo/n,fuentes,horizontal})}return out.sort((a,b)=>b.score-a.score||b.c0-a.c0||b.fuentes-a.fuentes||b.caminos-a.caminos||a.numero.localeCompare(b.numero))}
export type V9Row={numero:string;score:number;paths:number;birth:number;persist:number;gains:number;last_gain:number;sources:number;source_gain:number;c0:number;stale:boolean};
export function v9(hist:Tabla[]):V9Row[]{const snaps=hist.map((_,i)=>candidatos(tableroManual(hist.slice(0,i+1)).G)),current=snaps.at(-1)||new Map<string,P[][]>(),out:V9Row[]=[];for(const [numero,ps] of current){const counts=snaps.map(C=>C.get(numero)?.length||0),sources=snaps.map(C=>new Set((C.get(numero)||[]).flat().map(([,c])=>src(c))).size);let first=counts.findIndex(Boolean);if(first<0)first=counts.length;const persist=counts.filter(Boolean).length;let gains=0;for(let i=1;i<counts.length;i++)gains+=Math.max(counts[i]-counts[i-1],0);const last=counts.length>1?counts.at(-1)!-counts.at(-2)!:counts.at(-1)!,sg=sources.length>1?sources.at(-1)!-sources.at(-2)!:sources.at(-1)!,c0=ps.length?ps.filter(p=>p.some(([,c])=>src(c)===0)).length/ps.length:0,birth=first===0?1:Math.max(0,.65-.15*first),persistence=persist/counts.length,reinforcement=Math.min(gains,8)/8,recent=Math.max(Math.min(last,4),0)/4,convergence=sources.at(-1)!/hist.length,newsource=Math.max(Math.min(sg,2),0)/2,conf=Math.min(Math.log1p(ps.length)/Math.log(9),1),stale=counts.length>=3&&persist>=3&&last<=0&&sg<=0;let score=.18*birth+.12*c0+.16*persistence+.22*reinforcement+.13*recent+.12*convergence+.05*newsource+.02*conf;if(stale)score-=.10;out.push({numero,score,paths:ps.length,birth:first,persist,gains,last_gain:last,sources:sources.at(-1)!,source_gain:sg,c0,stale})}return out.sort((a,b)=>b.score-a.score||b.last_gain-a.last_gain||b.gains-a.gains||a.numero.localeCompare(b.numero))}
export function conviccion(R:V9Row[]){if(R.length<2)return 'BAJA';const gap=R[0].score-R[1].score;if(R[0].score>=.72&&gap>=.025)return 'ALTA';if(R[0].score>=.55)return 'MEDIA';return 'BAJA'}
const V11F=['v7_gap12','v7_gap15','v7_sd','v8_gap12','v8_gap15','v8_sd','v9_gap12','v9_gap15','v9_sd','v8_paths1','v8_c0','v8_sources','v8_horizontal','v9_paths1','v9_birth','v9_persist','v9_gains','v9_last_gain','v9_sources','v9_source_gain','v9_c0','v9_stale'];
const V13F=['r7','r8','r9','p7','p8','p9','sources','best_rank','rank_sum','rr_sum','s7_z','s8_z','s9_z'];
const V14F=['margin','max_conf','conf_spread','conf_V7','conf_V8','conf_V9','challenger_is_v8','challenger_is_v9',...V11F];
function mean(a:number[]){return a.reduce((x,y)=>x+y,0)/a.length}function popsd(a:number[]){const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))}function samplesd(a:number[]){if(a.length<2)return 1;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))||1}
function topStats(a:number[]){const x=a.slice(0,5);return [a.length>1?a[0]-a[1]:0,a.length>4?a[0]-a[4]:0,x.length?popsd(x):0]}
function telemetry(R7:V7Row[],R8:V8Row[],R9:V9Row[]){const [a,b,c]=topStats(R7.map(x=>x.score)),[d,e,f]=topStats(R8.map(x=>x.score)),[g,h,i]=topStats(R9.map(x=>x.score)),x8=R8[0],x9=R9[0];return {v7_gap12:a,v7_gap15:b,v7_sd:c,v8_gap12:d,v8_gap15:e,v8_sd:f,v9_gap12:g,v9_gap15:h,v9_sd:i,v8_paths1:x8?.caminos||0,v8_c0:x8?.c0||0,v8_sources:x8?.fuentes||0,v8_horizontal:x8?.horizontal||0,v9_paths1:x9?.paths||0,v9_birth:x9?.birth||0,v9_persist:x9?.persist||0,v9_gains:x9?.gains||0,v9_last_gain:x9?.last_gain||0,v9_sources:x9?.sources||0,v9_source_gain:x9?.source_gain||0,v9_c0:x9?.c0||0,v9_stale:Number(x9?.stale||false)}}
function knn(rows:number[][],nfeat:number,x:number[],k:number,ntarget:number){const mu:number[]=[],sd:number[]=[];for(let j=0;j<nfeat;j++){const col=rows.map(r=>r[j]);mu[j]=mean(col);sd[j]=popsd(col)||1}const q=x.map((v,j)=>(v-mu[j])/sd[j]),ds=rows.map((r,i)=>({i,d:Math.sqrt(q.reduce((s,v,j)=>s+(v-(r[j]-mu[j])/sd[j])**2,0))})).sort((a,b)=>a.d-b.d).slice(0,Math.min(k,rows.length));const out:number[]=[];for(let t=0;t<ntarget;t++){let num=0,den=0;for(const z of ds){const w=1/(z.d+.5);num+=rows[z.i][nfeat+t]*w;den+=w}out[t]=num/den}return out}
function v11Action(tel:Record<string,number>){const p=knn(TRAIN_V11,V11F.length,V11F.map(f=>tel[f]),40,3),conf={V7:p[0],V8:p[1],V9:p[2]};let chosen:'V7'|'V8'|'V9'='V7';for(const m of ['V8','V9'] as const)if(conf[m]>conf[chosen])chosen=m;return {chosen,conf}}
export type V13Row={cand:string;meta:number;sources:number;best_rank:number;rr_sum:number};
function v13Rank(R7:V7Row[],R8:V8Row[],R9:V9Row[]):V13Row[]{const L7=R7.slice(0,10).map(x=>x.numero),L8=R8.slice(0,10).map(x=>x.numero),L9=R9.slice(0,10).map(x=>x.numero),S7=new Map(R7.slice(0,10).map(x=>[x.numero,x.score])),S8=new Map(R8.slice(0,10).map(x=>[x.numero,x.score])),S9=new Map(R9.slice(0,10).map(x=>[x.numero,x.score])),union=[...new Set([...L7,...L8,...L9])].sort(),raw:any[]=[];for(const s of union){const ranks=[L7,L8,L9].map(L=>L.includes(s)?L.indexOf(s)+1:11),pres=ranks.map(r=>Number(r<=10));raw.push({cand:s,r7:ranks[0],r8:ranks[1],r9:ranks[2],p7:pres[0],p8:pres[1],p9:pres[2],sources:pres.reduce((a,b)=>a+b,0),best_rank:Math.min(...ranks),rank_sum:ranks.reduce((a,b)=>a+b,0),rr_sum:ranks.filter(r=>r<=10).reduce((a,r)=>a+1/r,0),s7:S7.get(s),s8:S8.get(s),s9:S9.get(s)})}for(const c of ['s7','s8','s9']){const good=raw.map(r=>r[c]).filter((x:any)=>x!==undefined) as number[],m=good.length?mean(good):0,sd=good.length>1?samplesd(good):1;for(const r of raw)r[c+'_z']=r[c]===undefined?-2:(r[c]-m)/sd}for(const r of raw){const x=V13F.map(f=>r[f]);r.meta=knn(TRAIN_V13,V13F.length,x,180,1)[0]}return raw.sort((a,b)=>b.meta-a.meta||b.rr_sum-a.rr_sum||a.cand.localeCompare(b.cand)).map(r=>({cand:r.cand,meta:r.meta,sources:r.sources,best_rank:r.best_rank,rr_sum:r.rr_sum}))}
function v14Action(tel:Record<string,number>,conf:Record<'V7'|'V8'|'V9',number>,v11:'V7'|'V8'|'V9'){const vals=Object.values(conf),feat:any={...tel,conf_V7:conf.V7,conf_V8:conf.V8,conf_V9:conf.V9,margin:Math.max(...vals)-conf.V7,max_conf:Math.max(...vals),conf_spread:Math.max(...vals)-Math.min(...vals),challenger_is_v8:Number(v11==='V8'),challenger_is_v9:Number(v11==='V9')},p=knn(TRAIN_V14,V14F.length,V14F.map(f=>feat[f]),350,3),ev={V7:p[0],V11:p[1],V13:p[2]},alt:'V11'|'V13'=ev.V11>=ev.V13?'V11':'V13',action:'V7'|'V11'|'V13'=ev[alt]-ev.V7>.01?alt:'V7';return {action,ev}}
function twoDigits(lists:Record<string,string[]>){const C=new Map<string,number>();for(const L of Object.values(lists)){const seen=new Set<string>();for(const n of L){const d=n.slice(-2);if(!seen.has(d)){C.set(d,(C.get(d)||0)+1);seen.add(d)}}}return [...C].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}
export function calcularVF(hist:Tabla[]){const R7=v7(hist),R8=v8(hist),R9=v9(hist),R13=v13Rank(R7,R8,R9),tel=telemetry(R7,R8,R9),v11=v11Action(tel),v14=v14Action(tel,v11.conf,v11.chosen),lists={V7:R7.slice(0,10).map(x=>x.numero),V8:R8.slice(0,10).map(x=>x.numero),V9:R9.slice(0,10).map(x=>x.numero),V13:R13.slice(0,10).map(x=>x.cand)},engine5={V7:lists.V7.slice(0,5),V8:lists.V8.slice(0,5),V9:lists.V9.slice(0,5),V13:lists.V13.slice(0,5)};const final=v14.action==='V7'?engine5.V7:v14.action==='V13'?engine5.V13:engine5[v11.chosen],votes5=new Map<string,number>(),votes10=new Map<string,number>();for(const m of ['V7','V8','V9'] as const){for(const n of engine5[m])votes5.set(n,(votes5.get(n)||0)+1);for(const n of lists[m])votes10.set(n,(votes10.get(n)||0)+1)}const consensus=[...votes5].filter(([,c])=>c>=2).map(([n])=>n),hidden:string[]=[];for(const m of ['V7','V8','V9'] as const)for(const n of lists[m].slice(5,10))if(!votes5.has(n)&&votes10.get(n)===1&&!hidden.includes(n))hidden.push(n);const alts:string[]=[];for(const m of ['V7','V8','V9','V13'] as const)for(const n of engine5[m])if(!final.includes(n)&&!alts.includes(n))alts.push(n);return {v7:R7.slice(0,10),v8:R8.slice(0,10),v9:R9.slice(0,10),v13:R13.slice(0,10),v11:v11.chosen,conf:v11.conf,v14:v14.action,ev:v14.ev,top2:final.slice(0,2),top5:final,ocultos:hidden.slice(0,5),alternativos:alts.slice(0,5),consenso:consensus,dos:twoDigits(lists).slice(0,10),conviccionV9:conviccion(R9)}}