export const TURNOS=['Previa','Primera','Matutino','Vespertino','Nocturno'] as const;
export const JURS=['Ciudad','Provincia','Córdoba','Santa Fé','Entre Ríos','Montevideo'] as const;
export type Tabla=Record<string,string>;
type P=[number,number];
const DIRS:P[]=[]; for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)if(a||b)DIRS.push([a,b]);
const mas11=(n:string)=>String((Number(n.padStart(4,'0').slice(-2))+11)%100).padStart(2,'0');
export function tablero(hist:Tabla[]){const G:(string|null)[][]=[]; for(const j of JURS){const row:(string|null)[]=[]; for(const t of hist){const n=t[j]; if(n&&n!=='----') row.push(...mas11(n).split('')); else row.push(null,null)} G.push(row)} return G}
function candidatos(G:(string|null)[][]){const out=new Map<string,P[][]>(); const R=G.length,C=G[0]?.length||0; for(let r=0;r<R;r++)for(let c=0;c<C;c++){if(G[r][c]==null)continue; for(const d1 of DIRS){const a:P=[r+d1[0],c+d1[1]]; if(a[0]<0||a[0]>=R||a[1]<0||a[1]>=C||G[a[0]][a[1]]==null)continue; for(const d2 of DIRS){const b:P=[a[0]+d2[0],a[1]+d2[1]]; if(b[0]<0||b[0]>=R||b[1]<0||b[1]>=C||G[b[0]][b[1]]==null||(b[0]===r&&b[1]===c))continue; const s=`${G[r][c]}${G[a[0]][a[1]]}${G[b[0]][b[1]]}`; const q=out.get(s)||[];q.push([[r,c],a,b]);out.set(s,q)}}} return out}
const src=(c:number)=>Math.floor(c/2);
export type Rank={numero:string;score:number;paths:number;c0:number;sources:number;lastGain?:number;gains?:number};
export function v8(hist:Tabla[]):Rank[]{const G=tablero(hist), C=candidatos(G), total=Math.max(hist.length,1), out:Rank[]=[]; for(const [numero,ps] of C){const n=Math.max(ps.length,1); const c0=ps.filter(p=>p.some(x=>src(x[1])===0)).length/n; const fuentes=new Set(ps.flat().map(x=>src(x[1]))).size/total; const horizontal=ps.filter(p=>new Set(p.map(x=>x[0])).size===1).length/n; const confianza=Math.min(Math.log1p(ps.length)/Math.log(9),1); out.push({numero,score:.55*c0+.30*fuentes+.05*horizontal+.10*confianza,paths:ps.length,c0,sources:fuentes})} return out.sort((a,b)=>b.score-a.score||b.c0-a.c0||b.sources-a.sources||b.paths-a.paths||a.numero.localeCompare(b.numero))}
export function v9(hist:Tabla[]):Rank[]{const snaps=hist.map((_,i)=>candidatos(tablero(hist.slice(0,i+1)))); const current=snaps[snaps.length-1]||new Map(),out:Rank[]=[]; for(const [numero,ps] of current){const counts=snaps.map(C=>C.get(numero)?.length||0); const sc=snaps.map(C=>new Set((C.get(numero)||[]).flat().map(x=>src(x[1]))).size); let first=counts.findIndex(Boolean);if(first<0)first=counts.length; const persist=counts.filter(Boolean).length; let gains=0;for(let i=1;i<counts.length;i++)gains+=Math.max(counts[i]-counts[i-1],0); const last=counts.length>1?counts.at(-1)!-counts.at(-2)!:counts.at(-1)!; const sg=sc.length>1?sc.at(-1)!-sc.at(-2)!:sc.at(-1)!; const c0=ps.length?ps.filter(p=>p.some(x=>src(x[1])===0)).length/ps.length:0; const birth=first===0?1:Math.max(0,.65-.15*first), persistence=persist/counts.length, reinforcement=Math.min(gains,8)/8,recent=Math.max(Math.min(last,4),0)/4, convergence=sc.at(-1)!/hist.length,newsource=Math.max(Math.min(sg,2),0)/2,conf=Math.min(Math.log1p(ps.length)/Math.log(9),1); let score=.18*birth+.12*c0+.16*persistence+.22*reinforcement+.13*recent+.12*convergence+.05*newsource+.02*conf; if(counts.length>=3&&persist>=3&&last<=0&&sg<=0)score-=.10;out.push({numero,score,paths:ps.length,c0,sources:sc.at(-1)!,lastGain:last,gains})} return out.sort((a,b)=>b.score-a.score||(b.lastGain||0)-(a.lastGain||0)||(b.gains||0)-(a.gains||0)||a.numero.localeCompare(b.numero))}
export function resumen(hist:Tabla[]){const a=v8(hist),b=v9(hist); const top8=a.slice(0,10).map(x=>x.numero),top9=b.slice(0,10).map(x=>x.numero); const votes=new Map<string,number>();[...top8,...top9].forEach(n=>votes.set(n,(votes.get(n)||0)+1)); const principal=[...new Set([...top8.slice(0,5),...top9.slice(0,5)])].sort((x,y)=>(votes.get(y)||0)-(votes.get(x)||0)).slice(0,5); const hidden=[...new Set([...top8.slice(5),...top9.slice(5)])].filter(n=>!principal.includes(n)&&votes.get(n)===1).slice(0,5); const d=new Map<string,number>();[...top8,...top9].forEach(n=>{const x=n.slice(-2);d.set(x,(d.get(x)||0)+1)});return {v8:a.slice(0,10),v9:b.slice(0,10),principal,hidden,dos:[...d].sort((x,y)=>y[1]-x[1]||x[0].localeCompare(y[0])).slice(0,5)}}
